# Generated by Django 5.1.2 on 2025-01-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('JUDGE', 'Judge'), ('CLERK', 'Clerk'), ('LAWYER', 'Lawyer')], max_length=20),
        ),
    ]
