# Generated by Django 5.0.2 on 2024-10-22 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cases.case')),
                ('clerk', models.ForeignKey(limit_choices_to={'role': 'clerk'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_as_clerk', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules_as_judge', to=settings.AUTH_USER_MODEL)),
                ('lawyers', models.ManyToManyField(limit_choices_to={'role': 'lawyer'}, related_name='schedules_as_lawyers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
