# Generated by Django 5.1.2 on 2025-01-21 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['scheduled_date']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='clerk',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lawyers',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='cases.case'),
        ),
    ]
