# Generated by Django 5.1.2 on 2025-01-24 19:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('description', models.TextField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='cases.case')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_proceedings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
