# Generated by Django 5.1.2 on 2025-01-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0001_initial'),
    ]

    operations = [
    ]
