# Generated by Django 5.1.2 on 2025-01-21 19:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('proceedings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceeding',
            name='date',
        ),
        migrations.RemoveField(
            model_name='proceeding',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='proceeding',
            name='outcome',
        ),
        migrations.AddField(
            model_name='proceeding',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_proceedings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='cases.case'),
        ),
    ]
