# Generated by Django 5.1.2 on 2025-01-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_lawyers_case_lawyer'),
        ('documents', '0001_initial'),
        ('judgements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='linked_case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='linked_judgment',
        ),
        migrations.AddField(
            model_name='document',
            name='linked_case',
            field=models.ManyToManyField(blank=True, related_name='documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_judgment',
            field=models.ManyToManyField(blank=True, related_name='documents', to='judgements.judgement'),
        ),
    ]
