# Generated by Django 5.1.2 on 2025-01-21 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('judgements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_of_judgment', models.DateField()),
                ('references', models.TextField(blank=True, help_text='References or citations used in this judgment', null=True)),
                ('attachments', models.FileField(blank=True, help_text='Additional documents', null=True, upload_to='judgements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cases.case')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_judgment'],
            },
        ),
        migrations.DeleteModel(
            name='Judgment',
        ),
    ]
