# Generated by Django 5.0.2 on 2024-10-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('plaintiff', models.CharField(max_length=255)),
                ('defendant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('closed', 'Closed'), ('appealed', 'Appealed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases_as_judge', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ManyToManyField(limit_choices_to={'role': 'lawyer'}, related_name='cases_as_lawyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
