# Generated by Django 5.1.2 on 2025-01-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='lawyer',
            new_name='lawyers',
        ),
    ]
