# Generated by Django 5.1.2 on 2025-01-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_lawyer_case_lawyers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='lawyers',
            new_name='lawyer',
        ),
    ]
