# Generated by Django 5.1.2 on 2025-01-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_plaintiff_column'),
        ('cases', '0002_case_created_by'),
    ]

    operations = [
    ]
